import { MigrationInterface, QueryRunner } from "typeorm";

export class RefactorEntity1704122209639 implements MigrationInterface {
    name = 'RefactorEntity1704122209639'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_9a5f6868c96e0069e699f33e124"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_2d404aa7aa4a0404eafd1840915"`);
        await queryRunner.query(`ALTER TABLE "address" DROP CONSTRAINT "FK_54c170d5fedd92b7265601b1672"`);
        await queryRunner.query(`ALTER TABLE "address" DROP CONSTRAINT "FK_44ac16d8d6eed5e0d5aa00e6d47"`);
        await queryRunner.query(`ALTER TABLE "products" RENAME COLUMN "organization_id" TO "branch_id"`);
        await queryRunner.query(`CREATE TABLE "category" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "name" character varying NOT NULL, "description" character varying, "slug" character varying NOT NULL DEFAULT uuid_generate_v4(), "branch_id" integer, CONSTRAINT "PK_9c4e4a89e3674fc9f382d733f03" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "per_descriptions"`);
        await queryRunner.query(`ALTER TABLE "organizations_branch" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "organizations_branch" DROP COLUMN "branch_name"`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "website"`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "image_url"`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "tax_id"`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "company_name"`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "tel"`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "note"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "address" DROP COLUMN "organization_id"`);
        await queryRunner.query(`ALTER TABLE "address" DROP COLUMN "subdistrict"`);
        await queryRunner.query(`ALTER TABLE "address" DROP COLUMN "organization_branch_id"`);
        await queryRunner.query(`ALTER TABLE "user_profiles" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`ALTER TABLE "theme_settings" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "theme_settings" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "theme_settings" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "theme_settings" ADD "slug" character varying NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "slug" character varying NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "branch_id" integer`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "organization_id" integer`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "slug" character varying NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "branch_id" integer`);
        await queryRunner.query(`ALTER TABLE "organizations_branch" ADD "active" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "active" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "business_desc" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "organization_type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "description" character varying`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "is_vat_registered" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "image_url" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "website" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "organization_id" integer`);
        await queryRunner.query(`ALTER TABLE "settings" ADD CONSTRAINT "UQ_d5bc871126b26b4fb1b9c743825" UNIQUE ("organization_id")`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "branch_id" integer`);
        await queryRunner.query(`ALTER TABLE "settings" ADD CONSTRAINT "UQ_e061efb50fe828776f19c5d9ba6" UNIQUE ("branch_id")`);
        await queryRunner.query(`ALTER TABLE "address" ADD "sub_district" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "address" ADD "settings_id" integer`);
        await queryRunner.query(`ALTER TABLE "address" ADD "user_profile_id" integer`);
        await queryRunner.query(`ALTER TABLE "address" ADD "customer_id" integer`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role_id" integer`);
        await queryRunner.query(`ALTER TABLE "users" ADD "branch_id" integer`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "name" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "permissions"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "permissions" jsonb NOT NULL DEFAULT '{"manageUsers":false,"manageRoles":false,"manageProjects":false,"manageProducts":false,"readAnalytics":false,"manageFinance":false,"manageSettings":false,"manageOrganization":false,"isOwner":false}'`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "bank_name" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "bank_account_name" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "bank_account_no" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "bank_branch" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "category" ADD CONSTRAINT "FK_16dcaf904b91226a3ba6950b5f0" FOREIGN KEY ("branch_id") REFERENCES "organizations_branch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_9a5f6868c96e0069e699f33e124" FOREIGN KEY ("category_id") REFERENCES "category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_de720484cb95d8752861e507921" FOREIGN KEY ("branch_id") REFERENCES "organizations_branch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "FK_b56499e5cc774ef0e1b9a0be138" FOREIGN KEY ("branch_id") REFERENCES "organizations_branch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "FK_c328a1ecd12a5f153a96df4509e" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_2ae4f4add790956c0f16a48cb74" FOREIGN KEY ("branch_id") REFERENCES "organizations_branch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "settings" ADD CONSTRAINT "FK_d5bc871126b26b4fb1b9c743825" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "settings" ADD CONSTRAINT "FK_e061efb50fe828776f19c5d9ba6" FOREIGN KEY ("branch_id") REFERENCES "organizations_branch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "address" ADD CONSTRAINT "FK_3e104beacb0770efbb81a97d3c9" FOREIGN KEY ("settings_id") REFERENCES "settings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "address" ADD CONSTRAINT "FK_0de3bf817c2dd82b0f8361ddae7" FOREIGN KEY ("user_profile_id") REFERENCES "user_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "address" ADD CONSTRAINT "FK_9c9614b2f9d01665800ea8dbff7" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_5a58f726a41264c8b3e86d4a1de" FOREIGN KEY ("branch_id") REFERENCES "organizations_branch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_5a58f726a41264c8b3e86d4a1de"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "address" DROP CONSTRAINT "FK_9c9614b2f9d01665800ea8dbff7"`);
        await queryRunner.query(`ALTER TABLE "address" DROP CONSTRAINT "FK_0de3bf817c2dd82b0f8361ddae7"`);
        await queryRunner.query(`ALTER TABLE "address" DROP CONSTRAINT "FK_3e104beacb0770efbb81a97d3c9"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP CONSTRAINT "FK_e061efb50fe828776f19c5d9ba6"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP CONSTRAINT "FK_d5bc871126b26b4fb1b9c743825"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_2ae4f4add790956c0f16a48cb74"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "FK_c328a1ecd12a5f153a96df4509e"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "FK_b56499e5cc774ef0e1b9a0be138"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_de720484cb95d8752861e507921"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_9a5f6868c96e0069e699f33e124"`);
        await queryRunner.query(`ALTER TABLE "category" DROP CONSTRAINT "FK_16dcaf904b91226a3ba6950b5f0"`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "bank_branch" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "bank_account_no" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "bank_account_name" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "bank_name" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "permissions"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "permissions" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "name" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "branch_id"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role_id"`);
        await queryRunner.query(`ALTER TABLE "address" DROP COLUMN "customer_id"`);
        await queryRunner.query(`ALTER TABLE "address" DROP COLUMN "user_profile_id"`);
        await queryRunner.query(`ALTER TABLE "address" DROP COLUMN "settings_id"`);
        await queryRunner.query(`ALTER TABLE "address" DROP COLUMN "sub_district"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP CONSTRAINT "UQ_e061efb50fe828776f19c5d9ba6"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "branch_id"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP CONSTRAINT "UQ_d5bc871126b26b4fb1b9c743825"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "organization_id"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "website"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "image_url"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "is_vat_registered"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP COLUMN "organization_type"`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "business_desc"`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "active"`);
        await queryRunner.query(`ALTER TABLE "organizations_branch" DROP COLUMN "active"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "branch_id"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "slug"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "organization_id"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "branch_id"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "slug"`);
        await queryRunner.query(`ALTER TABLE "theme_settings" DROP COLUMN "slug"`);
        await queryRunner.query(`ALTER TABLE "theme_settings" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "theme_settings" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "theme_settings" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_profiles" ADD "address" character varying`);
        await queryRunner.query(`ALTER TABLE "address" ADD "organization_branch_id" integer`);
        await queryRunner.query(`ALTER TABLE "address" ADD "subdistrict" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "address" ADD "organization_id" integer`);
        await queryRunner.query(`ALTER TABLE "settings" ADD "address" jsonb NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "note" character varying`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "tel" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "company_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "tax_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "image_url" character varying`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "website" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "is_active" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "organizations_branch" ADD "branch_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organizations_branch" ADD "status" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "per_descriptions" character varying NOT NULL`);
        await queryRunner.query(`DROP TABLE "category"`);
        await queryRunner.query(`ALTER TABLE "products" RENAME COLUMN "branch_id" TO "organization_id"`);
        await queryRunner.query(`ALTER TABLE "address" ADD CONSTRAINT "FK_44ac16d8d6eed5e0d5aa00e6d47" FOREIGN KEY ("organization_branch_id") REFERENCES "organizations_branch"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "address" ADD CONSTRAINT "FK_54c170d5fedd92b7265601b1672" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_2d404aa7aa4a0404eafd1840915" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_9a5f6868c96e0069e699f33e124" FOREIGN KEY ("category_id") REFERENCES "product_category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
